targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - argument_type_not_assignable
            - implicit_dynamic_parameter
            - unused_element
